# Generated by Selenium IDE
import time
import pytest
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.select import Select
import pytest
from selenium import webdriver


@pytest.fixture(scope="class")
def setup():
    global driver
    # driver = webdriver.Chrome(executable_path="C:\\chromedriver.exe")
    driver = webdriver.Chrome()
    driver.maximize_window()

    return driver


class TestDefaultSuite:
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_login(self):
        self.driver.get("https://sarkaripariksha.com/")
        self.driver.maximize_window()
        self.driver.delete_all_cookies()
        time.sleep(2)
        self.driver.find_element(By.LINK_TEXT, "Login / Register").click()
        time.sleep(2)
        self.driver.find_element(By.ID, "a").send_keys("8434506689")
        self.driver.find_element(By.ID, "b").send_keys("123456")
        time.sleep(2)
        self.driver.find_element(By.ID, "authenticate_login").click()
        time.sleep(2)
        self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(2) > li").click()
        time.sleep(2)
        self.driver.find_element(By.LINK_TEXT, "Start Now").click()
        self.driver.find_element(By.NAME, "btn_start_test").click()
        self.driver.find_element(By.ID, "chk_accept").click()
        self.driver.find_element(By.ID, "srt_eng").click()
        self.driver.find_element(By.ID, "start_test").click()
        time.sleep(3)
        self.driver.find_element(By.ID, "option_4_1").click()
        time.sleep(2)
        self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(2) > #submit_1 > .tt_next_btn").click()
        time.sleep(2)
        self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(2) > #submit_2 > .tt_next_btn").click()
        time.sleep(2)
        self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(2) > #submit_3 > .tt_next_btn").click()
        time.sleep(2)
        self.driver.find_element(By.CSS_SELECTOR, "#ques_4 > #contentdiv .radio:nth-child(5) > .fontControl").click()
        time.sleep(2)
        self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(2) > #submit_4 > .tt_next_btn").click()
        time.sleep(2)
        self.driver.find_element(By.ID, "medium_5").click()
        time.sleep(2)
        dropdown = self.driver.find_element(By.ID, "medium_5")
        time.sleep(2)
        select = Select(dropdown)
        time.sleep(2)
        select.select_by_visible_text("Hindi")
        self.driver.find_element(By.ID, "medium_5").click()
        time.sleep(2)
        select = Select(dropdown)
        time.sleep(2)
        select.select_by_visible_text("English")
        self.driver.find_element(By.CSS_SELECTOR, "#option_4_5 > p").click()
        time.sleep(2)
        self.driver.find_element(By.CSS_SELECTOR, ".float-right > #submit_5 > .mark_rev_next").click()
        time.sleep(2)
        self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(2) > #submit_5 > .tt_next_btn").click()
        time.sleep(2)
        self.driver.find_element(By.CSS_SELECTOR, "#ques_6 > #contentdiv .radio:nth-child(5) > .fontControl").click()
        time.sleep(2)
        self.driver.close()
        self.driver.quit()
